### ISSUE TITLE
-bash: syntax error near unexpected token `newline', error when attempt to run PlasClass

### ISSUE THREAD

**Issue by ysawires12345678** [Shamir-Lab/PlasClass#10]
Hello,
I installed Ubuntu 18.04 on windows 10 background , presumably came with Python 2.7 & PIP (already installed). I did install python  3.6.9 then upgraded the PIP package, created environment then classification. PlasClass was installed as advised and tested as recommended.
so once at the command prompt " (classification-env) ysawires@SMAH4:~/PlasClass$";  Python version is 3.6.9 and PIP version 9.0.1.
 the fasta file containing contigs was linerized (as the test file) using fasta tools and placed in the home directory. permission were changed as needed.
I used the command " python classify_fasta.py -f <fasta file> -o <output file> -p <default: 8> ; then I got this message
-bash: syntax error near unexpected token `newline
I appreciate your help to solve this

**Comment by dpellow** [comment]
Okay it seems that this error means that there is something wrong with the input of the command itself. What was the exact command that you used?
It should be: python classify_fasta.py -f <input fasta name> -o <output file name> -p <# of threads>
Where you replace the <parameter> options with the file names etc that you want. The -p parameter is optional and you can just leave it out if you want the default value.

Please let me know if that solved the problem.

**Comment by ysawires12345678** [comment]
Hello,
Thank you for your prompt answer, I tried the following and  received different errors
First

python classify_fasta.py -f <ABDU01.1.fsa_nt> -o <ABDU01.1.fsa_nt>
-bash: syntax error near unexpected token `newline'

second time

 python classify_fasta.py -f <ABDU01.1.fsa_nt> -o <ABDU01.1.fsa_nt> -p
Traceback (most recent call last):
  File "classify_fasta.py", line 6, in <module>
    from plasclass import plasclass_utils as utils
  File "/home/ysawires/PlasClass/plasclass/plasclass_utils.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

3rd time

python classify_fasta.py -f <ABDU01.1.fsa_nt> -o <ABDU01.1.fsa_nt> -p<>
-bash: syntax error near unexpected token `newline'

**Comment by dpellow** [comment]
The exact command should be 
`python classify_fasta.py -f ABDU01.1.fsa_nt -o ABDU01.1.fsa_nt.out`

The angle brackets are not part of the name, and are the cause of the bash error. I'm assuming you want to write the output to a different file and bit overwrite the input file so I gave it a different name. If you don't want a different number if threads than the default you leave it out.

I'm not sure why the second time seemed to work differently, but you need to have numpy and  all the other prerequisites installed. Note that if you install from bioconda it will automatically install all of the requirements. You can do this by creating a new conda environment: `conda create --name plasclass_env python=3.7` (adjust as appropriate for your python version but it needs to be python3 and beloe python3.8.)
Then activate the environment: `conda activate plasclass_env`.
Then install plasclass: `conda install -c bioconda plasclass`

**Comment by ysawires12345678** [comment]
it worked and I got my first report; Thank very much you for your help. The cut off in your publication is set for >0.5. if there are several contigs with this probability value, I would imagine that you start with the highest value first (some isolates can have up to 5 plasmids)?

**Comment by ysawires12345678** [comment]
what would be the exact default command for training?

**Comment by dpellow** [comment]
That is great. The score is a probability of being a plasmid, and you can choose whichever cutoff you like - 0.5, 0.7, 0.9, depending on what you require.
Note that the prediction and probability will be most accurate for longer contigs.

**Comment by dpellow** [comment]
The default training will be `python train.py -p <plasmid file> -c <chromosome file> -o <output directory>`. Where you replace all the angle bracket variable names with the actual names of your files.
