### ISSUE TITLE
How long does the training module take to finish one job

### ISSUE THREAD

**Issue by ysawires12345678** [Shamir-Lab/PlasClass#11]
Hello,
I ran the following command on the training module and it is not coming back to the command prompt?

 python train.py -p strain_13_plasmid.txt -c strain_13_chromosome.txt -o output_directory -n 16 -k 7 -l 10000

**Comment by dpellow** [comment]
It could depend on how much training data you are using. How long has it been running? How many sequences are in the training data?

What stage of the training did it get to - i.e. what messages have been printed out so far?

**Comment by ysawires12345678** [comment]
the chromosome file has one fully assembled chromosome (one contig 3Mb) and similarly in the plasmid file (one contig 54kb). when I omitted the default (-n -k -l), the meassage came out "sampling 272 fragement of 1000kb; getting k-mer frequencies...) as I recall

**Comment by dpellow** [comment]
Thanks I am trying to understand if it is stuck, if there is a bug, or if it's taking a long time. Can you let me know what messages are printed out when using the command that you said was not finishing?

Did it finish in the case where you used the defaults?

I'm not sure it's a good idea to train it on one sequence, what are you expecting to find? The provided models are trained with tens of thousands of plasmids and bacterial sequences.

**Comment by ysawires12345678** [comment]
my understanding was to make it organism specific; however, if there is no need for training; this will less work for me? 
the message for this command "python train.py -p strain_13_plasmid.txt -c strain_13_chromosome.txt -o output_directory
is "Starting PlasClass training
Getting reference lengths
Sampling 272 fragments for length 1000
Getting k-mer frequencies"

**Comment by dpellow** [comment]
Based on this it seems like it gets into the kmer counting step but not to the training step. How many processors and how much RAM do you have on your system? Can you check the state of the process when it seems to be stuck?

I'm not sure what the meaning of an organism specific classifier would be - if you already know the genome of the bacteria and the plasmid can't you just check whether your sequence comes from one or the other?

**Comment by ysawires12345678** [comment]
yes there are sequenced genomes. however, Some of the isolates (there are over 100 isolates with wgs sequence in the NCBI database) can contain up to 4 different plasmids at a time. the other way is do sequence  alignments. yet isolating the plasmid sequences is more straight forward. On trying another classifier; ML-plasmid; at least one of the suggested contigs belonged to a plasmid (confirmed earlier by PCR before the genome was sequenced).
So I'm  comparing the out put of both and choosing the most probable ones and likely the second step would be alignment with known sequences 
RAM is 16Gb, not sure how many processor but it is   intel 3.40 GHz

**Comment by dpellow** [comment]
OK I'll address these in reverse order:

- I think that means you're probably on a desktop/laptop not a server? So you probably don't have too many processors either. The kmer counting step uses multithreading so my guess is that it gets into that step and then runs out of processors/RAM and just gets stuck. You can try using fewer processors - maybe 2, 4 or even just 1. Use the option `-n 4` or any other number of processors to use after the `-n`. If there is not enough RAM it may still get stuck but using fewer processes should help with this too.

- what are the results when you try to classify with PlasClass? (I assume you didn't have to retrain the model for MLplasmids, you shouldn't have to for PlasClass either)

- If you have contigs from a few known species with a few known plasmids I think BLASTing them against the references should find all the matches.

**Comment by dpellow** [comment]
@ysawires12345678 did one of the above work?

**Comment by ysawires12345678** [comment]
the training did not work on my computer possible b/c limited computational power. however, using Blast, 6 plasmid contigs were identified with a length close to the fully sequenced one. of those; PlasClass Identified 4 with value >0.7 and 2 with value 5.144...e-09 and 0.0034000
Thanks for your advise and help
