### ISSUE TITLE
Mixed case sequences cause PlasClass to run indefinitely.

### ISSUE THREAD

**Issue by cerebis** [Shamir-Lab/PlasClass#12]
PlasClass seems to run without end if supplied mixed case sequences.

A small assmebly of 4000 sequences, which includes sequences of mixed upper and lower case was left running overnight.
PlasClass was still running eight hours later with 32 cpus. The same sequence set made all uppercase takes perhaps a minute to analyse.

I see in the documentation that upper case is required, but the side-effect of not having uppercase is unexpected.

I suggest that PlasClass simply convert sequences on input and warn the user.

**Comment by dpellow** [comment]
Yes, this is a good idea but I guess it hasn't been needed yet. How did you get mixed case sequences?

I will merge the modification but can you first test how it affects timing - how much longer does it take to classify sequences that are already all uppercase?

**Comment by cerebis** [comment]
I was experimenting with NextPolish and couldn't figure out what was going
wrong later with PlasClass. As it turned out, NextPolish writes upper and
lower case. I haven't investigated the reason yet, but I expect it'll
signify regions of confidence (coverage).

**Comment by dpellow** [comment]
Fixed by pull request [#13](https://github.com/Shamir-Lab/PlasClass/pull/13)
