### ISSUE TITLE
Highly scoring plasmid in an organism where No plasmid is reported in Literature

### ISSUE THREAD

**Issue by Rohit-Satyam** [Shamir-Lab/PlasClass#14]
Dear Developer

I was trying to use PlasClass to score my contig as plasmid or not. Since the organism (The entire genus) is given to me `Tenacibaculum_dicentrarchi_gca_900239345`  [does not have plasmid](https://academic.oup.com/gbe/article/10/2/452/4817510) your tool still shows it contains plasmid:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ROHITS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ROHITS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Tenacibaculum_dicentrarchi_gca_900239345 | TDCHD05_Contig_17 | 0.954729 | >TDCHD05_Contig_17 dna:supercontig   supercontig:TdChD05_V1:TDCHD05_Contig_17:1:14961:1 REF | 14961
-- | -- | -- | -- | --

</body>

</html>
With such a high score and contig length is also high. How do I explain such discrepancy?

**Comment by dpellow** [comment]
I don't fully understand the question. What are you trying to classify, did you assemble a genome or metagenome from reads?
Plasmids can move between bacteria and may be found in different strains or individuals, the fact that a specific draft genome of your species didn't have plasmids doesn't mean that your sample won't.
