### ISSUE TITLE
How to determine whether it is plasmid according to destination file

### ISSUE THREAD

**Issue by XXanna** [Shamir-Lab/PlasClass#19]

**Comment by dpellow** [comment]
I'm not sure I understood what the question is. The output file gives a predicted probability of being a plasmid for each input sequence.

**Comment by XXanna** [comment]
Many thanks for your kind reply.
________________________________
发件人: dpellow ***@***.***>
发送时间: 2023年6月14日 1:51
收件人: Shamir-Lab/PlasClass ***@***.***>
抄送: ***@***.*** ***@***.***>; Author ***@***.***>
主题: Re: [Shamir-Lab/PlasClass] How to determine whether it is plasmid according to destination file (Issue #19)


I'm not sure I understood what the question is. The output file gives a predicted probability of being a plasmid for each input sequence.

―
