### ISSUE TITLE
Downloading required data

### ISSUE THREAD

**Issue by anuradhawick** [Shamir-Lab/PlasClass#2]
I am interested in the preprint posted on biorxiv. I would like to know how you download the data required for plasmid training and chromosome training. Do you have any scripts that I might re-use to obtain data.

Thank you

**Comment by dpellow** [comment]
PLSDB can be downloaded here: https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/
There are a few resources you can read to learn about how to download all bacterial genomes:
- https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/#allcomplete
- https://www.biostars.org/p/61081/
Hope that helps! BTW what are you hoping to do with the data?

**Comment by anuradhawick** [comment]
At first, I wish to reproduce the training and understand how PlasClass perform side by side with PlasFlow. Thanks for the reply. It's very helpful.
