### ISSUE TITLE
Score?

### ISSUE THREAD

**Issue by sjaenick** [Shamir-Lab/PlasClass#3]
Hi,

could you elaborate on the score that is assigned to each sequence? How should this be
interpreted?

Thanks.

**Comment by dpellow** [comment]
Sure - the score is assigned by a logistic regression classifier. It can be interpreted as a probability that the sequence is of plasmid origin. Closer to 1 is more probable that it is of plasmid origin, closer to 0 is more probable that it originates from a bacterial chromosome.

**Comment by bjtully** [comment]
What would be a reasonable score cutoff to have confidence that sequence is of plasmid origin? Anything >0.5? >0.9? Knowing that there is spectrum - but ideally looking for "high confidence" plasmids only.

**Comment by dpellow** [comment]
@bjtully It's a tradeoff between precision and recall.

A cutoff of 0.9 for longer (> 1-2 kb) sequences should pretty much yield only plasmids. For short sequences this cutoff will have lower confidence and for longer sequences you can lower the cutoff and still be pretty confident.

We've observed that the scores often take extreme values (at least for long sequences), so a lot of times there is not a big difference in using a cutoff of say 0.8 vs 0.7.

In practice, in our applications such as SCAPP, we use a score of 0.9 to have very high confidence that a sequence is plasmid.

**Comment by bjtully** [comment]
@dpellow Thanks!
