### ISSUE TITLE
Requesting help with model training 

### ISSUE THREAD

**Issue by anuradhawick** [Shamir-Lab/PlasClass#4]
https://github.com/Shamir-Lab/PlasClass/blob/1fa3ae4ce6e0c74fb69e3e843a22876bb4fe16e8/plasclass/train.py#L122

I am referencing the above link to a line of code that has caused some confusion. Is it expected to obtain sequences shorted that length (l) and use them with combining at the end, or should it be corrected as follows.

```python
def get_seqs(infile, inds_dict, l):
    ''' Create array of the sequences
    '''
    seqs = []
    fp = open(infile)
    for name,seq,_ in utils.readfq(fp):
        start_inds = inds_dict.get(name, [])
        for start_ind in start_inds:
            frag = seq[start_ind:start_ind+l]
            if len(frag) < l and len(seq) > l:
                frag += seq[:l-len(frag)]
            seqs.append(frag) # <<<<<<<<<<<<<<<<<<< changed indentation of the code line
    fp.close()
    return seqs
```

Thanks in advance

**Comment by dpellow** [comment]
Good catch, that is definitely a bug. I've pushed the fix.
