### ISSUE TITLE
scikit-learn version

### ISSUE THREAD

**Issue by emdyess** [Shamir-Lab/PlasClass#5]
Hi,

Thanks for the nice tool.  

When I run the classify_fasta.py script, I get a scikit-learn UserWarning: Trying to unpickle LogisticRegression from version 0.19.1 when using version 0.21.3.  This might lead to breaking code or invalid results.  A similar warning comes up for estimator StandardScaler.  

Setup.py sets scikit-learn=0.21.3.  

I get results, but I am wondering if this is a problem.  I am guessing that the models were trained under a different version of scikit-learn, and it is probably best to have the versions the same if possible.

Thanks!

**Comment by dpellow** [comment]
Yes PlasClass was originally written in Python2 and then ported to Python3. The models were trained and saved in a Python2 compatible version of sklearn which doesn't support Python3. I tested the Python2 and Python3 versions of PlasClass and had no problems or differences between the two.
